// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyRjX5HMUQ0JOJBP4bAIj4sdv_LkxjFA',
    appId: '1:753992964750:web:400e9e9dfc7828de8747df',
    messagingSenderId: '753992964750',
    projectId: 'todolist-fd19b',
    authDomain: 'todolist-fd19b.firebaseapp.com',
    storageBucket: 'todolist-fd19b.firebasestorage.app',
    measurementId: 'G-GFVQDJPTXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_H_zLUXSCE2z_pFd5guSEZapTIPo53WI',
    appId: '1:753992964750:android:458afc12b45d2e2a8747df',
    messagingSenderId: '753992964750',
    projectId: 'todolist-fd19b',
    storageBucket: 'todolist-fd19b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmajGEO-4jjD97SjaQLtmwVW2xL0z1VQQ',
    appId: '1:753992964750:ios:d882ad6b314da8518747df',
    messagingSenderId: '753992964750',
    projectId: 'todolist-fd19b',
    storageBucket: 'todolist-fd19b.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutterMoacir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmajGEO-4jjD97SjaQLtmwVW2xL0z1VQQ',
    appId: '1:753992964750:ios:d882ad6b314da8518747df',
    messagingSenderId: '753992964750',
    projectId: 'todolist-fd19b',
    storageBucket: 'todolist-fd19b.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutterMoacir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZyRjX5HMUQ0JOJBP4bAIj4sdv_LkxjFA',
    appId: '1:753992964750:web:a182de1627c98c648747df',
    messagingSenderId: '753992964750',
    projectId: 'todolist-fd19b',
    authDomain: 'todolist-fd19b.firebaseapp.com',
    storageBucket: 'todolist-fd19b.firebasestorage.app',
    measurementId: 'G-7FRFL5HB6N',
  );
}
